### ISSUE TITLE
Module "lib.js" not found

### ISSUE THREAD

**Issue by 710850609** [kangour/autojs_sdk#2]
你好。
1、我clone了你的仓库到本地，
2、然后在autojs_sdk文件夹下面创建了一个test.js的文件，
3、复制README.md里面的demo代码：

// 导入：从 lib.js 导入需要的方法
let { start_app, click_item, set_volume, wait_befor_click } = require('lib.js');

// 编写主函数：程序启动后执行的逻辑代码。
function main() {
    wait_befor_click('发现', '跳过')
    click_item('发现')
    click_item('每日推荐')
    click_item('播放全部')
    set_volume(30)
}

// 启动应用：传入参数依次为：主函数，要启动的 App 名称，当前应用描述，是否语音播报执行状态。
start_app(main, '网易云音乐', '播放日推', true)

4、最后在vscode远程调试手机，报下面的错误：
[Extension Host] 09:37:23.211/E: Error: Module "lib.js" not found. (file:///android_asset/modules/jvm-npm.js#89)Error: Module "lib.js" not found.    at Require (file:///android_asset/modules/jvm-npm.js:89:0)    at [remote]test.js:2:0

**Comment by 710850609** [comment]
找到问题了，是lib.js 没有保存到手机

**Comment by caijuanjuan** [comment]
> 找到问题了，是lib.js 没有保存到手机

你好，我也遇到了同样的问题，想请问下是保存到手机哪个文件夹呢，我导入到auto.js也还是会报同样的错误

**Comment by miaozilong** [comment]
如何保存到手机的?

**Comment by heibai6** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
